include-and-override=portal-developer.properties
setup.wizard.enabled=false

#SETUP WIZARD ##
# --------------------------------------------
admin.email.from.address=test@liferay.com
admin.email.from.name=Test Test
company.default.locale=pt_BR
company.default.time.zone=UTC
company.default.web.id=liferay.com
default.admin.email.address.prefix=test
database.indexes.update.on.startup=true
#liferay.home=/opt/liferay


#
# =========================================
# DATABASE (PostgreSQL)
# =========================================
#

jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.url=jdbc:postgresql://database:5432/lportal
jdbc.default.username=liferay
jdbc.default.password=liferay


#
# =========================================
# ELASTICSEARCH (REMOTE - ES7)
# =========================================
#

elasticsearch.connectionId=REMOTE
elasticsearch.operation.mode=REMOTE

elasticsearch.remote.cluster.connection.id=REMOTE
elasticsearch.remote.cluster.seed.hosts=["elasticsearch:9300"]

elasticsearch.index.number.of_shards=1
elasticsearch.index.number.of_replicas=1

#
# =========================================
# FILE STORAGE
# =========================================
#

dl.store.impl=com.liferay.portal.store.file.system.FileSystemStore
#liferay.home=/opt/liferay/data


#
# =========================================
# LOGGING
# =========================================
#

log.level=INFO